# Generated by Django 3.2.7 on 2021-09-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='user',
            new_name='owner',
        ),
    ]
